<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'name' => 'Notebook Dell Inspiron',
                'description' => 'Notebook de alta performance com processador Intel i7.',
                'price' => 4500.00,
                'image' => null,
                'reference' => 1001,
                'barcode' => 789100000001,
                'stock_quantity' => 15,
                'observation' => 'Garantia de 1 ano',
                'add_info' => 'Ideal para uso profissional',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Camiseta Básica Preta',
                'description' => 'Camiseta 100% algodão confortável e estilosa.',
                'price' => 59.90,
                'image' => null,
                'reference' => 1002,
                'barcode' => 789100000002,
                'stock_quantity' => 120,
                'observation' => 'Lavar à mão',
                'add_info' => 'Disponível em todos os tamanhos',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fone de Ouvido Bluetooth',
                'description' => 'Fone sem fio com cancelamento de ruído.',
                'price' => 299.90,
                'image' => null,
                'reference' => 1003,
                'barcode' => 789100000003,
                'stock_quantity' => 60,
                'observation' => 'Bateria de 20h',
                'add_info' => 'Compatível com Android e iOS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Smartphone Samsung Galaxy',
                'description' => 'Smartphone com câmera de 108MP e 256GB de armazenamento.',
                'price' => 3500.00,
                'image' => null,
                'reference' => 1004,
                'barcode' => 789100000004,
                'stock_quantity' => 30,
                'observation' => 'Desbloqueado',
                'add_info' => 'Dual chip',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tênis Esportivo Nike',
                'description' => 'Tênis leve e confortável para corrida e atividades físicas.',
                'price' => 320.00,
                'image' => null,
                'reference' => 1005,
                'barcode' => 789100000005,
                'stock_quantity' => 50,
                'observation' => 'Uso diário',
                'add_info' => 'Numeração do 37 ao 44',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Relógio Inteligente Apple Watch',
                'description' => 'Monitoramento de saúde, notificações e design elegante.',
                'price' => 2500.00,
                'image' => null,
                'reference' => 1006,
                'barcode' => 789100000006,
                'stock_quantity' => 25,
                'observation' => 'Garantia Apple',
                'add_info' => 'Pulseiras intercambiáveis',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mochila Executiva',
                'description' => 'Mochila resistente com compartimentos para notebook e acessórios.',
                'price' => 199.90,
                'image' => null,
                'reference' => 1007,
                'barcode' => 789100000007,
                'stock_quantity' => 70,
                'observation' => 'Impermeável',
                'add_info' => 'Cabe notebooks até 15,6"',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cadeira Gamer',
                'description' => 'Cadeira ergonômica com apoio para braços e ajuste de altura.',
                'price' => 899.90,
                'image' => null,
                'reference' => 1008,
                'barcode' => 789100000008,
                'stock_quantity' => 18,
                'observation' => 'Suporta até 120kg',
                'add_info' => 'Revestimento em couro sintético',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Teclado Mecânico RGB',
                'description' => 'Teclado mecânico com iluminação RGB e switches táteis.',
                'price' => 349.90,
                'image' => null,
                'reference' => 1009,
                'barcode' => 789100000009,
                'stock_quantity' => 40,
                'observation' => 'Switch azul',
                'add_info' => 'Cabo destacável',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Caneca Personalizada',
                'description' => 'Caneca de cerâmica com estampa divertida e resistente.',
                'price' => 39.90,
                'image' => null,
                'reference' => 1010,
                'barcode' => 789100000010,
                'stock_quantity' => 200,
                'observation' => 'Pode ir ao micro-ondas',
                'add_info' => 'Capacidade 350ml',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
